# This YAML file describes your package. Stack will automatically generate a
# Cabal file when you run `stack build`. See the hpack website for help with
# this file: <https://github.com/sol/hpack>.
name: instances-template
version: '0.0.0'
github: "githubuser/instances-template"
license: MIT
author: "Author name here"
maintainer: "Author name here"
# synopsis: A new Haskeleton package.
# description: instances-template is a new Haskeleton package.
# category: Other

extra-source-files:
- LICENSE.md
- package.yaml
- README.md
- stack.yaml

ghc-options: -Wall

library:
  dependencies:
  - base
  source-dirs: library

tests:
  instances-template-test-suite:
    source-dirs: test-suite
    main: Main.hs
    dependencies:
    - base
    - instances-template
    - quickcheck-classes-base
    - tasty
    - tasty-quickcheck
    - QuickCheck
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
